// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Vaziria/pkl/backend/pkgs/pkl_config"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	config, err := pkl_config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(config)
	if err != nil {
		return nil, err
	}
	migrationFunc := NewMigrationFunc(db)
	app := NewApp(config, db, migrationFunc)
	return app, nil
}
